config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :chatrooms do
    collection do
      get :search
    end
  	resource :chatroom_user_relationships
  	resources :messages
  end

  resources :direct_messages

  resources :contacts do
  	collection do
  		get :search_friends
  	end
  	member do
  		post :request_friendship
  		post :defriend_request
  		post :accept_friendship
  	end
  end

  root to: "chatrooms#index"

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_action :authenticate_user!
	layout "with_contact_list"

	def index
		if params[:q] && params[:q].values.reject(&:blank?).any?
			@q = User.all.ransack(params[:q])
			@finded_friends = @q.result - [current_user]
		else
			@q = current_user.friends.ransack(:id_eq => -1)
			@finded_friends = @q.result - [current_user]
		end
	end

	def show
		@friend = User.find(params[:id])
		unless current_user.is_friend_of?(@friend)
			redirect_to contacts_path
		end
	end

	def new
		
	end

	def edit
		
	end

	def request_friendship
		friend = User.find(params[:id])
		current_user.request_friendship_with(friend)
		redirect_to :back
	end

	def defriend_request
		friend = User.find(params[:id])
		current_user.defriend_with(friend)
		redirect_to :back
	end

	def accept_friendship
		friend = User.find(params[:id])
		current_user.accept_friendship_with(friend)
		redirect_to :back
	end

	def search_friends
		q = current_user.friends.ransack(username_or_email_cont: params[:query_str])
		@friends = q.result - [current_user]
	end

end

app/helpers/contacts_helper.rb
module ContactsHelper
	def render_friendship_status_with(user)
		friendship = current_user.friendship_with(user)
		unless friendship
			return link_to "申请添加好友", request_friendship_contact_path(id: user.id), method: :post, class: "btn btn-info btn-xs"
		end

		case friendship.status
		when "requested"
			link_to "同意成为好友", accept_friendship_contact_path(id: user.id), method: :post, class: "btn btn-success btn-xs"
		when "pending"
			"等待对方同意"
		when "accepted"
			"你们已经是好友"
		else
			raise "friendship的status有问题"
		end

	end

	def render_untreated_friendships_count_of(user)
		count = user.untreated_friendships_count
		if count > 0
			content_tag(:span, "#{count}", class: ["badge", "little_number"])
		else
			content_tag(:span, "", class: ["badge", "little_number"])
		end
	end
end

app/views/contacts/index.html.erb
<div id="adding-contact-container">
	
	<div id="adding-contact-search-section">
		<h5>添加联系人</h5>

		<div>
			<%= search_form_for @q, url: contacts_path do |f| %>
				<div class="input-group">
					<%= f.search_field :username_or_email_cont, :placeholder => "可输入用户名、邮箱进行搜索", class: "form-control" %>
					<span class="input-group-btn">
						<%= f.submit "搜索", class: "btn btn-default" %>
					</span>
				</div>
			<% end %>
		</div>
	</div>


	<div id="search-contact-result-section">
		<% @finded_friends.each do |finded_friend| %>
			<div class="media">
				<div class="media-left media-middle">
					<%= render_user_avatar_of(finded_friend, "45x45", "media-object") %>
				</div>
				<div class="media-body">
					<h6><%= finded_friend.username %></h6>
					<small><%= finded_friend.email %></small>
					<small class="pull-right friendship-status"><%= render_friendship_status_with(finded_friend) %></small>
				</div>
			</div>
		<% end %>
	</div>

</div>

app/views/contacts/search_friends.js.erb
str = "<%=j render partial: 'common/friend_list', locals: { friends: @friends } %>";
$("#friend-list-container").html(str);

app/views/contacts/show.html.erb
<div id="contact-show-container">

	<div class="media">
		<div class="media-body">
			<%= @friend.username %>
		</div>
		<div class="media-right">
			<%= render_user_avatar_of(@friend, "64x64", "media-object") %>
		</div>
	</div>

	<hr>
	
	<table class="user-detail-table">
		<tr>
			<th>Email: </th>
			<td><%= @friend.email %></td>
		</tr>
	</table>
	
	<div class="user-interactive-container">
		<div class="btn-group" id="start-talking-btn">
			<%= link_to "开始聊天", Chatroom.direct_message_for_users([current_user, @friend]), class:"btn btn-success btn-sm" %>
		</div>

		<div class="btn-group" id="defriend-btn">
			<%= link_to "解除好友关系", defriend_request_contact_path(id: @friend.id), method: :post, class: "btn btn-danger btn-xs" %>
		</div>
	</div>

</div>