config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :chatrooms do
    collection do
      get :search
    end
  	resource :chatroom_user_relationships
  	resources :messages
  end

  resources :direct_messages

  resources :contacts do
  	collection do
  		get :search_friends
  	end
  	member do
  		post :request_friendship
  		post :defriend_request
  		post :accept_friendship
  	end
  end

  root to: "chatrooms#index"

end

app/views/common/_chatrooms_list.html.erb
<ul class="nav nav-pills nav-stacked">
	<% chatrooms.order(updated_at: :desc).each do |chatroom| %>
		<li class="chatroom-list-cell">
			<%= link_to chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id} do %>
				<div class="media">
					<div class="media-left">
						<div class="group-avatars">
							<%= render_avatar_of(chatroom) %>
						</div>
						<%= render_unread_count_of(chatroom) %>
					</div>
					<div class="media-body">
						<div class="media-heading"><%= render_name_of(chatroom) %></div>
						<div class="media-subtitle"><%= chatroom.last_message_str %></div>
					</div>
				</div>
			<% end %>
		</li>
	<% end %>
</ul>

app/views/common/_friend_list.html.erb
<ul class="nav nav-pills nav-stacked">
	<% friends.each do |friend| %>
		<li class="friend-list-cell">
			<%= link_to contact_path(id: friend.id), data: {behavior: "chatroom-link", chatroom_id: Chatroom.direct_message_for_users([current_user, friend]).id } do %>
				<div class="media">
					<div class="media-left">
						<%= render_user_avatar_of(friend, "30x30", "media-object") %>
					</div>
					<div class="media-body">
						<h5 class="media-heading"><%= friend.username %></h5>
					</div>
				</div>
			<% end %>
		</li>
	<% end %>
</ul>

app/views/common/_sidebar.html.erb
<div class="text-center">
	<h5 id="sidebar-header">微信</h5>
	<small id="sidebar-username"><%= current_user.username if user_signed_in? %></small>
</div>
<ul class="nav nav-stacked" role="tablist">
	<% if user_signed_in? %>
		<li id="chatrooms-side-btn">
			<%= link_to chatrooms_path do %>
				<%= image_when_current_in_chatrooms %>
				<%= render_all_unread_count_of(current_user) %>
			<% end %>	
		</li>
		<li id="contacts-side-btn">
			<%= link_to contacts_path do %>
				<%= image_when_current_in_contacts %>
				<%= render_untreated_friendships_count_of(current_user) %>
			<% end %>
		</li>
	<% else %>
		<li><%= link_to "登录", new_user_session_path, id:"signin-button" %></li>
		<li><%= link_to "注册", new_user_registration_path, id:"signup-button" %></li>
	<% end %>
</ul>


<%= link_to "登出", destroy_session_path(current_user), method: :delete, id:"logout-button" if user_signed_in? %>