config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :chatrooms do
    collection do
      get :search
    end
  	resource :chatroom_user_relationships
  	resources :messages
  end

  resources :direct_messages

  resources :contacts do
  	collection do
  		get :search_friends
  	end
  	member do
  		post :request_friendship
  		post :defriend_request
  		post :accept_friendship
  	end
  end

  root to: "chatrooms#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FakeWeichat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container weichat-container">
      <div class="col-sm-1 weichat-sidebar">
        <%= render "common/sidebar" %>
      </div>

		  <div class="col-sm-11" id="user_sign_container">
	    	  <%= yield %>
	    </div>
    </div>
  </body>
</html>

app/views/layouts/with_chatroom_list.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FakeWeichat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	<div class="container weichat-container">
		<div class="col-sm-1 weichat-sidebar">
			<%= render "common/sidebar" %>
		</div>
		
		<div class="col-sm-4 chatroom-middle-bar" style="height: 100%;">
			<div id="chatroom-search-container" class="row text-center" style="height: 10%;">
				<div id="chatroom-search-head" class="form-inline">
					<%= text_field_tag 'search-chatrooms-field', nil, placeholder: "搜索聊天室", url: search_chatrooms_path %>

					<%= link_to "+", new_chatroom_path, class: "btn btn-default btn-xs", id:"create_new_chatroom_btn" %>
				</div>
			</div>

			<div class="row chatroom-list" id="chatrooms-list-container">
				<%= render partial: "common/chatrooms_list", locals: { chatrooms: current_user.chatrooms } %>
			</div>
		</div>

		<div class="col-sm-7" style="height: 100%;">
	    	<%= yield %>
	    </div>
    </div>
  </body>
</html>

app/views/layouts/with_contact_list.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FakeWeichat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<div class="container weichat-container">
		<div class="col-sm-1 weichat-sidebar">
			<%= render "common/sidebar" %>
		</div>

		<div class="col-sm-4" style="height: 100%;">
			<div id="friend-search-container" class="row text-center" style="height: 10%;">
				<div id="friend-search-head" class="form-inline">
					<%= text_field_tag 'search-friends-field', nil, placeholder: "搜索联系人", url: search_friends_contacts_path%>

					<%= link_to "+", contacts_path, class: "btn btn-default btn-xs ", id:"add_new_friend_btn" %>
				</div>
			</div>

			<div id="new-friend-requests" class="row">
				<%= link_to " > 新朋友", "#friends-request-list", data:{toggle: "collapse"}, id:"new-friend-requests-btn" %>
				<div class="collapse <%= "in" if current_user.untreated_friendships_count > 0 %>" id="friends-request-list">
					<% current_user.untreated_friends.each do |friend| %>
						<div class="media">
							<div class="media-left media-middle">
								<%= render_user_avatar_of(friend, "30x30", "media-object") %>
							</div>
							<div class="media-body">
								<h5 class="media-heading"><%= friend.username %></h5>
								<small class="pull-right friendship-status"><%= render_friendship_status_with(friend) %></small>
							</div>
						</div>
					<% end %>
				</div>
			</div>
			
			<div id="friend-list-container" class="row">
				<%= render partial: "common/friend_list", locals: {friends: current_user.friends} %>
			</div>

		</div>

		<div class="col-sm-7" style="height: 100%;">
	    	<%= yield %>
	    </div>
    </div>
  </body>
</html>